### PR TITLE
Run CI with fedora latest

### PR DESCRIPTION
**Pull request by streeve**
Previous issues with MPI prompted move to rawhide; issues noted in #803 with gtest caused unrelated failures

### CODE REVIEW

**Comment by streeve** [comment]
@aprokop this will fix the issue in your PR. I'm fine to merge and fix the docker build separately

**Comment by aprokop** [comment]
For some reason, there are still pending `fedora:rawhide` checks.

**Comment by junghans** [comment]
The cabana CI containers depend on the kokkos ci containers, but they haven't been updated for a while due to https://github.com/kokkos/ci-containers/issues/56.

**Comment by junghans** [comment]
> > The cabana CI containers depend on the kokkos ci containers, but they haven't been updated for a while due to [kokkos/ci-containers#56](https://github.com/kokkos/ci-containers/issues/56). So I believe `fedora:latest` is still F40 not F41 (previous rawhide).
> 
> Good to know - based on the comment in the CI here all I recall is that latest was failing due to MPI. Should we wait if it works now?

The kokkos containers got refreshed, I am rebuilding ours right now: https://github.com/ECP-copa/ci-containers/actions/runs/13066871276

**Comment by junghans** [comment]
Now there is a hypre issue:
```
#26 22.37 In file included from /home/kokkos/src/hypre/src/distributed_ls/pilut/DistributedMatrixPilutSolver.h:115,
#26 22.37                  from /home/kokkos/src/hypre/src/distributed_ls/pilut/comm.c:25:
#26 22.37 /home/kokkos/src/hypre/src/distributed_ls/pilut/./struct.h:43:26: error: 'bool' cannot be defined via 'typedef'
#26 22.37    43 |    typedef unsigned char bool;
#26 22.37       |                          ^~~~
#26 22.37 /home/kokkos/src/hypre/src/distributed_ls/pilut/./struct.h:43:26: note: 'bool' is a keyword with '-std=c23' onwards
#26 22.37 /home/kokkos/src/hypre/src/distributed_ls/pilut/./struct.h:43:4: warning: useless type name in empty declaration
#26 22.37    43 |    typedef unsigned char bool;
#26 22.37       |    ^~~~~~~
#26 22.37 gmake[2]: *** [CMakeFiles/HYPRE.dir/build.make:3901: CMakeFiles/HYPRE.dir/distributed_ls/pilut/comm.c.o] Error 1
#26 22.37 gmake[2]: *** Waiting for unfinished jobs....
#26 22.47 gmake[1]: *** [CMakeFiles/Makefile2:542: CMakeFiles/HYPRE.dir/all] Error 2
#26 22.47 gmake: *** [Makefile:136: all] Error 2
```
I believe this is due to a newer gcc, Is there a problem with bumping hypre to a more recent version.

On a sidenote, starting the Fedora 42 (next release), Fedora's hypre package will be build with CMake, hence we do not need to build it ourselves anymore.

**Review by aprokop — APPROVED** [review]
LGTM

**Comment by streeve** [comment]
> I believe this is due to a newer gcc, Is there a problem with bumping hypre to a more recent version.
> 

Maybe I missed something, but I didn't see any updates in their repo fixing that

**Comment by junghans** [comment]
> > I believe this is due to a newer gcc, Is there a problem with bumping hypre to a more recent version.
> 
> Maybe I missed something, but I didn't see any updates in their repo fixing that

I guess, we should report it up them then!
