### ISSUE TITLE
Problems updating Cabana and Kokkos

### ISSUE THREAD

**Issue by XzzX** [ECP-copa/Cabana#876]
I currently try to update MRMD (https://github.com/XzzX/mrmd) to use the newest Canaba (0.8) and Kokkos (5.2.1) versions. Unfortunately, I run into some compilation problems. Have you seen this kind of error messages? Can you give me some hints on how to solve it? Everything compiles with Kokkos 4.7.1 and Cabana 0.7.

```
/__w/mrmd/mrmd/mrmd-build/_deps/kokkos-src/core/src/Kokkos_View.hpp:172:9: error: no type named 'extents_type' in 'using Kokkos::Impl::BasicViewFromTraits<double* [1][3], Kokkos::LayoutCabanaSlice<13, 1, 3, 0, 0, 0, 0, 0>, Kokkos::HostSpace, Kokkos::MemoryTraits<25> >::mdspan_view_traits = struct Kokkos::Impl::MDSpanViewTraits<Kokkos::ViewTraits<double* [1][3], Kokkos::LayoutCabanaSlice<13, 1, 3, 0, 0, 0, 0, 0>, Kokkos::HostSpace, Kokkos::MemoryTraits<25> >, void, void>' {aka 'struct Kokkos::Impl::MDSpanViewTraits<Kokkos::ViewTraits<double* [1][3], Kokkos::LayoutCabanaSlice<13, 1, 3, 0, 0, 0, 0, 0>, Kokkos::HostSpace, Kokkos::MemoryTraits<25> >, void, void>'}
```
https://github.com/XzzX/mrmd/actions/runs/34112208397/job/101710774207

Thank you for your help!

**Comment by streeve** [comment]
Hey @XzzX newest master should work with a recent merge if you'd like to test - 0.8.1 is planned to include the same fix

**Comment by XzzX** [comment]
Thanks, seems to go into the right direction. Unfortunately, now GitHub runners run out-of-memory during actual instantiation of AoSoA views. This is also the case with my machine with a lot more memory. Unsure if this is a compiler problem or a code problem.
